package praktikum;
import java.util.*;

public class perpustakaanMain {
    public static void main(String[] args) {
        kategori teknologi = new kategori("Teknologi");
        teknologi.tambahBuku(new buku("The Swallows", Arrays.asList("Nicholas G. Carr"), "Teknologi", "Buku The Shallows karya Nicholas Carr ini menerangkan dengan begitu fasih tentang bagaimana perubahan mental model (cognitive shifting) terjadi pada manusia sejak adanya internet.", 2011, 1200000));
        teknologi.tambahBuku(new buku("Computer Architecture: A Quantitative Approach", Arrays.asList("David A. Patterson"), "Teknologi", "Buku yang membahas arsitektur komputer dengan pendekatan kuantitatif. Buku ini membahas berbagai topik, seperti hierarki memori, paralelisme, mesin virtual, dan memori Flash.", 1992, 450000));
        teknologi.tambahBuku(new buku("Matinya Kepakaran", Arrays.asList("Tom Nichols"), "Teknologi", "Jadi, buku ini menjelaskan tentang matinya kepakaran di era seperti sekarang. Dalam buku ini Tom Nichols menjelaskan beberapa penyebab dari matinya kepakaran. Matinya kepakaran bukan hanya disebabkan oleh internet yang mana sangat banyak informasi yang bisa kita dapatkan entah itu terbukti kebenarannya ataupun hanya sebatas hoax, tetapi banyak faktor yang menyebabkan matinya kepakaran.", 2017, 150000));
        teknologi.tambahBuku(new buku("The Code Breaker", Arrays.asList("Walter Isaacson"), "Teknologi", "membahas tentang pentingnya karya Doudna dalam penelitian penyuntingan gen CRISPR. Doudna memimpin labnya yang berbasis kolaborasi dan kerja sama lintas disiplin ilmu. Labnya berperan penting dalam mendiagnosis, menguji, dan melawan Covid-19.", 2021, 50000));
        teknologi.tambahBuku(new buku("Technopoly", Arrays.asList("Neil Postman"), "Teknologi", "Dalam buku yang berisi kritik budaya yang cerdas dan mendebarkan ini, penulis mencatat transformasi masyarakat dunia menjadi sebuah teknopoli: masyarakat yang tidak lagi hanya menggunakan teknologi sebagai sistem pendukung melainkan juga dibentuk olehnya. Penting untuk memahami bagaimana posisi teknologi di masa modern dan postmodern, namun juga penting untuk melihat kemungkinan-kemungkinan terburuk yang bisa terjadi di kemudian hari.", 1992, 90000));

        kategori filsafat = new kategori("Filsafat");
        filsafat.tambahBuku(new buku("Dunia Sophie", Arrays.asList("Jostein Gaarder"), "Filsafat", "Sophie merupakan seorang pelajar sekolah menegah yang berusia 14 tahun. Namun suatu hari setelah pulang sekolah, ia mendapatkan sebuah surat misterius yang hanya berisikan satu pertanyaan \"Siapa Kamu?\". Hal ini tentunya membuat Sophie heran, pada hari yang sama dia juga mendapatkan surat lain yang bertanya\"Dari manakah datangnya dunia?\". Hal ini tentunya membuat ia tersentak dari rutinitas hidup sehari-hari, surat itu selalu membuat Sophie mempertanyakan soal-soal mendasar yang tak pernah dipikirkannya selama ini.", 1991, 88000));
        filsafat.tambahBuku(new buku("Filosofi Teras", Arrays.asList("Henry Manampiring"), "Filsafat", "Filosofi Teras membahas tentang filsafat stoic yang dinilai mampu membekali manusia untuk tenang menghadapi persoalan.", 2018, 100000));
        filsafat.tambahBuku(new buku("The Passions of The Soul", Arrays.asList("Rene Descartes"), "Filsafat", "The Passions of the Soul adalah karya penting dalam korpus filsafat Ren Descartes yang membahas mengenai aspek kompleks dalam kehidupan manusia: emosi dan perasaan. Dalam karya ini, Descartes menghadirkan pandangan yang terperinci tentang sifat-sifat emosi dan bagaimana hubungan antara jiwa dan tubuh berkontribusi terhadap pengalaman emosional manusia. Karya ini tidak hanya mengungkapkan pandangan Descartes tentang sifat manusia, tetapi juga memberikan wawasan tentang bagaimana filsuf ini berusaha menggabungkan pandangan agama dan ilmiah dalam pemahaman tentang aspek-aspek inti keberadaan manusia.", 1649, 55000));
        filsafat.tambahBuku(new buku("Philosophy 101", Arrays.asList("Paul Kleinman"), "Filsafat", "Philosophy 101 cuts out the boring details and exhausting philosophical methodology instead. This book gives you a lesson in philosophy that keeps you engaged as you explore the fascinating history of human thought and inquisition. From Aristotle and Heidegger to free will and metaphysics, Philosophy 101 is packed with hundreds of entertaining philosophical tidbits, illustrations, and thought puzzles that you won't be able to find anywhere else.", 2013, 78000));
        filsafat.tambahBuku(new buku("Alam Pikiran Yunani", Arrays.asList("Mohammad Hatta"), "Filsafat", "Sebagai buku yang menceritakan tentang orang-orang Yunani yang mencoba menjelaskan dunia dengan bertanya, buku ini memberikan gambaran yang utuh tentang itu. Alam pikiran yunani dapat dianggap semacam resume atau ringkasan sejarah tradisi berpikir orang-orang Yunani. Mulai dari mereka mempertanyakan dari apa bahan dasar alams semesta sampai dengan kematian filsuf paling bijak Sokrates setelah dihukum dengan meminum racun, karena raja menganggap Sokrates telah menambahkan ajaran sesat. Sampai sekolah Epikuros berdiri dengan logika, fisika, dan etik sebagai mata pelajaran utama, sampai sekolah Stoa yang merambah negara dan masyarakat hingga sekolah skeptis Akademia dan aliran neo-phytagoras oleh Platinos yang religius.",1941, 75000));

        kategori sejarah = new kategori("Sejarah");
        sejarah.tambahBuku(new buku("Sapiens", Arrays.asList("Yuval Noah Harari"), "Sejarah", "Riwayat Singkat Umat Manusia karya Yuval Noah Harari mengulas sejarah manusia dari masa prasejarah hingga abad ke-21. Buku ini memadukan sains dan sejarah untuk menelaah perkembangan manusia.", 2011, 76000));
        sejarah.tambahBuku(new buku("Guns, Germs, and Steel", Arrays.asList("Jared Diamond"), "Sejarah", "Rangkuman Riwayat Masyarakat Manusia mencoba menjelaskan mengapa peradaban Eurasia dan Afrika Utara bertahan dan menaklukkan yang lain, sambil menentang gagasan bahwa hegemoni Eurasia disebabkan oleh segala bentuk keunggulan intelektual, moral, atau genetik yang melekat pada Eurasia. Jared Diamond berpendapat bahwa kesenjangan dalam kekuasaan dan teknologi antara masyarakat manusia terutama berasal dari perbedaan lingkungan, yang diperkuat oleh berbagai putaran umpan balik positif. Ketika perbedaan budaya atau genetik disukai orang Eurasia, misalnya, bahasa tertulis atau perkembangan resistensi orang Eurasia terhadap penyakit endemik, ia menegaskan bahwa keuntungan ini terjadi karena pengaruh geografi pada masyarakat dan budaya. Misalnya dengan memfasilitasi perdagangan dan perdagangan antara budaya yang berbeda, serta tidak melekat dalam genom Eurasia.",1997, 88500));
        sejarah.tambahBuku(new buku("Bumi Manusia", Arrays.asList("Pramoedya Ananta Toer"), "Sejarah", "Bercerita tentang perjalanan hidup Minke, seorang pemuda pribumi pada masa kolonial. Novel ini mengisahkan perjuangan Minke melawan ketidakadilan dan diskriminasi.", 1980, 67000));
        sejarah.tambahBuku(new buku("Hiroshima", Arrays.asList("John Richard Hersey"), "Sejarah", "Buku ini mengisahkan enam orang yang selamat dari bom atom yang dijatuhkan di Hiroshima.",1946, 32000));
        sejarah.tambahBuku(new buku("Max Havelaar", Arrays.asList("Eduard Douwes Dekker"), "Sejarah", "bercerita tentang sistem tanam paksa yang diterapkan pemerintah kolonial Belanda di Indonesia pada abad ke-19. Buku ini menggambarkan kekerasan Belanda terhadap penduduk asli, terutama di daerah Lebak, Banten.", 1860, 65000));

        kategori agama = new kategori("Agama");
        agama.tambahBuku(new buku("Mere Christianity", Arrays.asList("C.S. Lewis"), "Agama", "Mere Christianity bertujuan untuk membuktikan kepada kaum skeptis yang berakal sehat bahwa Tuhan memang ada. Buku ini dimulai dengan bukti logis bagi Tuhan Kristen. Lewis menentang ateisme dengan menunjukkan apa yang disebutnya Hukum Sifat Manusia, atau kebenaran universal dan absolut. Lewis mengemukakan poin penting ketika ia menulis bahwa pencarian seseorang akan Tuhan tidak dapat dilakukan secara terpisah. Lewis mendefinisikan Roh Kudus sebagai persatuan — hubungan — antara Bapa dan Putr", 1952, 75000));
        agama.tambahBuku(new buku("Pengantar Sejarah Dogma Kristen", Arrays.asList("Bernhard Lose"), "Agama", "Dengan  singkat, sistematis dan luar biasa terangnya buku ini menguraikan bagaimana perkembangan dogma-dogma dalam periode-periode sejarah Gereja, sejak abad pertama hingga kini. Usaha ini merupakan penjelajahan dan diskusi terbentuknya dogma-dogma dan doktrin-doktrin itu, satu per satu, yang telah ditetapkan dan diperdebatkan di sepanjang abad-abad yang lalu, dalam usaha Gereja memproklamasikan pesana Yesus Kristus bagi masing-masing periode. Dalam buku ini, Bernhard Lohse berhasil memadukan berbagai hal yang paling dtuhkan oleh para mahasiswa teologi dan  orang-orang yang berminat di bidang dogmatika Kristen. Yaitu kebutuhan  untuk mendaptkan bacaan yang dapat meringkaskan sejarah dogma-dogma yang  demikian panjang itu secara menyeluruh dan sistematis, tanpa memberikan  kesan naif. Bernhard Lohse adalah Guru besar dalam bidang sejarah Gereja dan Sejarah Teologi pada Universitas Hambrug, Jerman Barat.", 1966, 90000));
        agama.tambahBuku(new buku("Maaf Tuhan, Aku Hampir Menyerah", Arrays.asList("Alfi Alghazi"), "Agama", "Dalam buku Maaf Tuhan, Aku Hampir Menyerah ini membahas mengenai lika-liku perjalanan manusia yang tidak selamanya berjalan dengan baik. Setiap perjalanan kehidupan akan ada hambatan dan rintangan yang kadang begitu sulit untuk dilewati.Dari masalah-masalah dalam kehidupan ini kita diajak untuk selalu berpikir positif dan pantang menyerah.", 2019, 74000));
        agama.tambahBuku(new buku("Pengantar Teologi", Arrays.asList("Nico Syukur Dister"), "Agama", "Buku ini membahas teologi sistematika yang terdiri dari tiga bagian yaitu prolegomena tentang epistemologi teologi, Allah penyelamat yang membahas Trinitas, Kristologi, Pneumatologi, dan ekonomi keselamatan yang membahas penciptaan, soteriologi, eklesiologi, sakramen, Mariologi, dan eskatologi.", 1999, 67000));
        agama.tambahBuku(new buku("Daily Dose of Light", Arrays.asList("Ahmad Fuadi"), "Agama", "Daily Dose of Light berisi kutipan-kutipan ayat Alquran yang ditampilkan dengan ilustrasi yang asyik. Adapun kutipan-kutipan ayat Aquran diharapkan bisa menjadi penyemangat untuk pembaca setiap harinya.", 2020, 55000));

        kategori psikologi = new kategori("Psikologi");
        psikologi.tambahBuku(new buku("Thinking, Fast and Slow", Arrays.asList("Daniel Kahneman"), "Psikologi", "Buku ini menjelajahi dua sistem pemikiran yang beroperasi di dalam pikiran kita: Sistem 1 (pemikiran cepat) dan Sistem 2 (pemikiran lambat). Kahneman menguraikan bagaimana kedua sistem ini mempengaruhi pengambilan keputusan kita, penilaian, dan perilaku sehari-hari. Buku ini menawarkan wawasan yang mendalam tentang proses berpikir dan memberikan pemahaman yang lebih baik tentang kelemahan dan bias yang dapat mempengaruhi kita dalam pengambilan keputusan. Kahneman menjelaskan konsep-konsep seperti pemikiran intuitif, efek heuristik, pengaruh emosi dalam penilaian, dan banyak lagi.", 2011, 89000));
        psikologi.tambahBuku(new buku("The Power of Habit", Arrays.asList("Charles Duhigg"), "Psikologi", "Kebiasaan adalah Rahasia Keberhasilan. Travis, seorang pemuda broken home degan orang tua pecandu obat, berkali-kali dipecat dari pekerjaan karena tidak bisa mengendalikan emosi. Namun sesudah menjalani pelatihan pegawai Starbucks yang mengajarkan kekuatan tekad, Travis kini sukses menjadi manajer dua cabang kafe terkenal itu. Seorang CEO baru memegang salah satu perusahaan raksasa Amerika. Perintah pertamanya adalah menumbuhkan kepedulian keselamatan kerja-dan hasilnya saham perusahaan itu, Alcoa, menjadi salah satu yang berkinerja terbaik di Dow Jones.", 2012, 54000));
        psikologi.tambahBuku(new buku("The Art of Choosing", Arrays.asList("Sheena Iyengar"), "Psikologi", "Buku ini membahas berbagai aspek pilihan, termasuk bagaimana orang membuat pilihan dan dampaknya terhadap kehidupan. Buku ini juga membahas faktor-faktor yang memengaruhi pilihan, seperti budaya dan lingkungan.", 2010, 123000));
        psikologi.tambahBuku(new buku("Man's Search for Meaning", Arrays.asList("Viktor Frankl"), "Psikologi", "Viktor Frankl pernah berada di empat kamp kematian Nazi yang berbeda, termasuk Auschwitz, antara tahun 1942 dan 1945. Dia bertahan hidup, sementara orangtuanya, saudara laki-laki, dan istrinya yang tengah hamil akhirnya tewas dalam kamp. Di dalam keganasan dan kekejian kamp, Frankl yang juga seorang psikiater belajar menemukan makna hidup. Menurutnya, kita tidak dapat menghindari penderitaan, tetapi kita dapat memilih cara mengatasinya, menemukan makna di dalamnya, dan melangkah maju dengan tujuan baru. Teori Frankl, yang dikenal sebagai logoterapi, menjelaskan bahwa dorongan utama kita dalam hidup bukanlah kesenangan, tetapi penemuan dan pencarian dari apa yang secara pribadi kita temukan bermakna.", 1946, 70000));
        psikologi.tambahBuku(new buku("The Social Animal", Arrays.asList("Elliot Aronson"), "Psikologi", "Buku ini adalah buku yang unik dalam menjelaskan perilaku manusia sebagai objek dari berbagai riset ilmu; mulai dari ilmu sosial, perilaku, psikologi, hingga neuroscience.", 1972, 75000));

        kategori politik = new kategori("Politik");
        politik.tambahBuku(new buku("The Communist Manifesto", Arrays.asList("Karl Marx", "Friedrich Engels"), "Politik", "Marx dan Engels adalah tokoh utama dalam gerakan sosialis internasional. Mereka percaya bahwa kapitalisme, dengan segala ketidakadilannya, pada akhirnya akan runtuh dan digantikan oleh sistem sosial yang lebih adil. The Communist Manifesto ditulis sebagai panduan untuk memahami dan mengarahkan perubahan ini. Buku ini menguraikan teori-teori dasar mereka tentang sejarah, ekonomi, dan politik, serta menyerukan kepada kelas pekerja untuk bersatu dan mengambil alih kendali atas sarana produksi.", 1848, 45000));
        politik.tambahBuku(new buku("Democracy in America", Arrays.asList("Alexis de Tocqueville"), "Politik", "The primary focus of Democracy in America is an analysis of why republican representative democracy has succeeded in the United States while failing in so many other places. Also, Tocqueville speculates on the future of democracy in the United States, discussing possible threats to democracy and possible dangers of democracy. These include his belief that democracy has a tendency to degenerate into \"soft despotism\" as well as the risk of developing a tyranny of the majority. He observes that the strong role religion played in the United States was due to its separation from the government, a separation all parties found agreeable. Tocqueville also outlines the possible excesses of passion for equality among men, foreshadowing the totalitarian states of the twentieth century as well as the severity of contemporary political correctness.", 1835, 70000));
        politik.tambahBuku(new buku("Keadaban Politik", Arrays.asList("Lutfhi J. Kurniawan"), "Politik", "Sebuah buku yang berisi pengalaman, pergulatan pemikira & nurani tentang kekuasaan dan kewarasan. Seringkali oran menjadi tidak waras ketika berebut kekuasaan atau ketika sudah berkuasa. Buku ini mengingatkan dengan keras bahwa akal sehat publik wajib menjadi pijar api yang menyala benderang.", 2023, 70000));
        politik.tambahBuku(new buku("How Democracies Die", Arrays.asList("Steven Levitsky", "Daniel Ziblatt"), "Politik", "Buku ini membahas tentang kemunduran demokrasi dan bagaimana para pemimpin yang terpilih secara sah dapat secara perlahan melemahkan proses demokrasi demi memperkuat kekuasaan mereka. Buku ini juga memberikan peringatan serius tentang dampak Partai Republik dan kepemimpinan Donald Trump terhadap demokrasi di Amerika Serikat.", 2018, 75000));
        politik.tambahBuku(new buku("The Prince", Arrays.asList("Niccolò Machiavelli"), "Politik", "Seorang Penguasa yang bijaksana harus membangun kekuasaannya berdasarkan apa yang ia sendiri kuasai, bukan berdasarkan apa yang orang lain kuasai. la harus berusaha agar ditakuti dan dicintai. Buku ini mengupas pengembangan pemikiran untuk meraih cita-cita. Sebuah dokumen sosial dan politik yang penting dan sudah menjadi bagian dari perkembangan ilmu sosial-politik di dunia. Buku ini tetap kontekstual di setiap masa. Berisi tentang pemikiran dan ajaran-ajaran pemerintahan, pemerintahan, serta mampu memberi inspirasi bagi pemimpin-pemimpin abad ini.", 1532, 80000));

        kategori fiksi = new kategori("Fiksi");
        fiksi.tambahBuku(new buku("1984", Arrays.asList("George Orwell"), "Fiksi", "Buku ini bercerita tentang suatu masa di sekitar tahun 1984. Orwell menggambarkan masa itu sebagai masa yang penuh penderitaan. Dalam semesta “1984”, dunia dibagi menjadi tiga poros kuasa; Oceania, Eurasia, dan Eastasia. Setiap negara dipimpin oleh satu partai. Mereka semua berhaluan sosialis. Setiap negara juga menerapkan sistem totalitarian. Novel ini fokus menceritakan Oceania, khususnya London dimana sang tokoh utama hidup. Oceania dipimpin oleh Big Brother (Bung Besar) yang wajahnya tertera di poster-poster di berbagai penjuru negara. Sistem kediktatoran yang diterapkan membuat semua warganya harus tunduk dan patuh. Kedisiplinan ini sifatnya menyeluruh. Mulai dari jadwal bangun tidur, hiburan, buku yang dibaca, bahkan ekspresi muka dan pikiran.", 1949, 70000));
        fiksi.tambahBuku(new buku("The Great Gatsby", Arrays.asList("F. Scott Fitzgerald"), "Fiksi", "Nick Carraway, seorang narator yang pindah ke Long Island untuk bekerja di dunia keuangan, menjadi saksi dan peserta dalam peristiwa-peristiwa yang melibatkan tokoh-tokoh utama seperti Jay Gatsby, seorang miliarder misterius yang mengadakan pesta megah di rumahnya setiap malam; Daisy Buchanan, sepupu Nick yang merupakan cinta pertama Gatsby; dan Tom Buchanan, suami Daisy yang kaya dan kasar. Gatsby memiliki obsesi terhadap masa lalu dan menginginkan cinta Daisy yang pernah ia kenal saat masih muda. Gatsby mencurahkan usahanya untuk memenangkan kembali hati Daisy, yang telah menikah dengan Tom. Intrik cinta segitiga ini mengarah pada kejadian-kejadian tragis di akhir novel.", 1925, 80000));
        fiksi.tambahBuku(new buku("Bumi", Arrays.asList("Tere Liye"), "Fiksi", "Buku ini menceritakan petualangan tiga remaja, Raib, Seli, dan Ali, yang memiliki kemampuan khusus dan ditakdirkan untuk menyelamatkan Bumi dari ancaman klan jahat pimpinan Tamus.", 2014, 99000));
        fiksi.tambahBuku(new buku("Sang Alkemis", Arrays.asList("Paulo Coelho"), "Fiksi", "Secara garis besar, Sang Alkemis bercerita tentang petualangan Santiago, seorang anak gembala, yang ingin mencari harta terpendam. Alih-alih harta dalam bentuk fisik, ia justru menemukan harta di dalam diri yang tak ternilai jumlahnya.", 1988, 100000));
        fiksi.tambahBuku(new buku("5 cm", Arrays.asList("Donny Dhirgantoro"), "Fiksi", "Buku 5 Cm menceritakan perjalanan tujuh tahun persahabatan yang mengesankan antara lima anak muda penuh semangat: Arial, Riani, Zafran, Ian, dan Genta. Mereka bukan sekadar teman, tetapi sahabat sejati yang saling mendukung demi mewujudkan impian masing-masing. Namun, kebosanan merayap dan mengubah arah hidup mereka ketika mereka memutuskan untuk menjalani tiga bulan tanpa komunikasi. Tiga bulan perpisahan menjadi masa yang membentuk karakter mereka, menggantikan kebosanan dengan kekayaan hati yang baru. Pertemuan setelah tiga bulan menjadi puncak emosional yang merayakan perjalanan baru mereka. Perjalanan ini bukan hanya tentang mendaki puncak Mahameru, gunung tertinggi di Pulau Jawa, tetapi juga tentang perjalanan menuju keyakinan, mimpi, cita-cita, dan cinta.", 2005, 15000));

        List<kategori> daftarkategori = Arrays.asList(teknologi, filsafat, sejarah, agama, psikologi, politik, fiksi);
        

        for (kategori kategori : daftarkategori) {
            kategori.tampilkanBuku();
        }
        
        teknologi.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        filsafat.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        sejarah.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        agama.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        psikologi.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        politik.tampilkanPersentaseKesamaan();
        System.out.println("---------------------------------------------");
        System.out.println();
        fiksi.tampilkanPersentaseKesamaan();
    }
}
